all:
	g++ incremental.cpp -L../cryptominisat/build/lib -lcryptominisat5 -I../cryptominsat/build/include -I../cryptominisat/build/cmsat5-src -o incremental
	cp ../cryptominisat/build/lib/libcryptominisat.so.5.8 libcryptomnisat.so.5.8
